### ISSUE TITLE
Add screenshots to README [documentation_improvement]

### ISSUE THREAD

**Issue by selivan** [dmsimard/ara#116]
It would be nice to have a couple of screenshots on top of README, now you have to search youtube to get and idea what it is like.

**Comment by dmsimard** [comment]
@selivan So there's screenshots (that I should update! Thanks!) in the documentation http://ara.readthedocs.io/en/latest/faq.html#what-does-the-web-interface-look-like

Perhaps I should make that more obvious in the README but I'd like to keep it as lightweight as possible -- we can do something in the middle. I'll figure something out so that it's easier to find what the UI looks like.

Thanks !

**Comment by selivan** [comment]
Something like this: https://github.com/selivan/ara/blob/patch-1/README.rst

I suppose, you put some effort in creating logo and would like to show it. But if you want new users interested immediately after they somehow stumbled upon a link, this is much better.

**Comment by dmsimard** [comment]
Not a bad idea, I'll think of something. Thanks for the feedback !

**Comment by dmsimard** [comment]
@selivan I've now added an explicit header in the README: https://github.com/openstack/ara#what-does-the-web-interface-look-like-

The preview video and screenshots have been updated as well.

Thanks.

**Comment by selivan** [comment]
@dmsimard Yep, now it's much easier to guess what it does it look like :) I still think that big juicy screenshot right at the top of README would give more "wow, I want this" effect on passing by strangers.
