### ISSUE TITLE
Purge databases

### ISSUE THREAD

**Issue by Ekouyoja** [dmsimard/ara#119]
Hi,

First of all I would like to thank you for your work.
And i need your help to know how do I empty the database ?

**Comment by dmsimard** [comment]
@Ekouyoja completely emptying the database ? Deleting the database file (if you are running sqlite) or dropping and re-creating the database (if running mysql) is probably the best way ?

You can otherwise delete individual playbooks with the "ara playbook delete" command. You can retrieve the playbook UUIDs from the "ara playbook list" command.

**Comment by Ekouyoja** [comment]
Thank you for your response
Can I delete multiple Playbook simultaneously for exemple delete all playbook before 23 march.
I use the default database (explore product), sqlite i mean

**Comment by dmsimard** [comment]
There is no feature right now to delete data "older than X". You would need to implement your own scripted logic, like ``ara playbook list | logic | xargs ara playbook delete``.

You can pass multiple playbook UUIDs to the "ara playbook delete" command, just separate them by spaces.

**Comment by Ekouyoja** [comment]
Okay thank you for the reply ;)
Have nice day
