### ISSUE TITLE
better use of screen real estate (reduce waste)

### ISSUE THREAD

**Issue by ssbarnea** [dmsimard/ara#126]
I think that you will find the photo self-explanatory. I marked all the useless space with red-rectangles.

![170823-1056](https://user-images.githubusercontent.com/102495/29610500-3d6ffdec-87f2-11e7-8d0b-fea90cc9691b.png)

**Comment by dmsimard** [comment]
Definitely open to contributions for improving the frontend, I'm definitely not an expert for that :)

I settled for something that was a compromise between small and large resolutions.
Removing that whitespace would mean that the UI would look silly at larger resolutions because of the amount of whitespace *inside* the panels (rather than *outside* the panels).

Issues for ARA are not tracked here, this repository is only kept for historical purposes.
I'll close this, could you open it here please: https://storyboard.openstack.org/#!/project/843
