### ISSUE TITLE
Ansible does not report the URL of saved ARA reports

### ISSUE THREAD

**Issue by ssbarnea** [dmsimard/ara#127]
It seems that by default, even when ARA is loaded and is successfully saving the execution reports inside the database there is zero feedback/indication on the console.

We need to post a message like: `ARA reports available at http://1.2.3.4:9191/subdir/`

**Comment by dmsimard** [comment]
The callback is not aware of where the reports are/will be hosted. This will be even more true as components are decoupled from each other in ARA 1.0.
Reports can also be generated statically and hosted somewhere entirely unexpected... on any host, on any port.

I would rather not display anything at all rather than display something that has chances of being inaccurate.

The user/operator has knowledge of where the reports will be hosted.
I think if you really wanted, you could probably add a debug task at the end of the playbook run or something like that ? Or a simple callback that knows where the reports will be located and could print something on the ``v2_playbook_on_stats`` hook.

If necessary, please re-open this on the proper bug tracker: https://storyboard.openstack.org/#!/project/843
