### ISSUE TITLE
aborted ansible returns 500 error

### ISSUE THREAD

**Issue by stokkie90** [dmsimard/ara#57]
Aborted ansible playbook runs will result in an internal server error when selecting the run on the webpage.

**Comment by dmsimard** [comment]
Thanks, should be easy enough to reproduce.

**Comment by dmsimard** [comment]
@stokkie90, this should be fixed with the latest commits to the master branch. It has not yet been released in a tag or in pypi, there are some more changes we want to do before doing so.

To benefit from this change, it requires a slight database schema change. We do not yet provide sql migrations but we will once we declare some level of stability on it. You should not be able to reproduce this if you use a new database. We've also covered this case in unit tests to prevent regressions from affecting this.

Thanks for reporting.

**Comment by stokkie90** [comment]
Thanks for the fast fix.
