### ISSUE TITLE
ui/ux suggestions

### ISSUE THREAD

**Issue by TristanCacqueray** [dmsimard/ara#76]
here are some note that may improve usability of static file rendering:
* replace the top-level index.html landing page by the all hosts list (host/index.html),
* reverse the order of playbook list so that most recent run are display on top,
* add a task pop-down to display détail in playbook view.

**Comment by dmsimard** [comment]
Thanks for the feedback.

> here are some note that may improve usability of static file rendering

There is (currently) no difference between the static and the dynamic version, so I edited the issue title. Changes done to the UI will affect both versions.

> replace the top-level index.html landing page by the all hosts list (host/index.html)

Doing away with the home page is not necessarily a bad idea but I feel the playbook list would be a better fit than the host list. @larsks and I wanted to put the latest playbook runs on the home page at some point. That said, I think the home page could provide some value in conveying what the app is about but the message that is displayed there has almost not changed since the very early prototype. We could do better and have panels with a snapshot of the recently involved playbooks and/or hosts.

> reverse the order of playbook list so that most recent run are display on top,

Ah, so in the navbar the order is properly set to the most recent at the top but the playbook list has that order reversed. Sure.

> add a task pop-down to display détail in playbook view.

What would this look like ? Can you explain your idea a bit more ?

**Comment by TristanCacqueray** [comment]
You're welcome, note that ARA is very useful as it is now and this issue is a minor improvement :)
 
The entrypoint index.html could use a similar output as the [gate-tempest-dsvm-full](http://logs.openstack.org/29/312929/9/check/gate-tempest-dsvm-full/e568041/) openstack job: It gives pointer to the logs and show a "Guide to Tempest Results Runs" bellow. It seems like a good middle-ground where familiar users can quickly access what they need, and new users can learn what is ARA and how to use it.

Then about the "task pop-down", it's actually a wish for the "Tasks results" list. The idea is to get tasks details on the same page to avoid opening new windows. For example the last failed task could automatically show its details below, and clicking on a task row could show a tooltip/dropdown box with the task detail so that it's easy to investigate a playbook run using a single browser tab.

**Comment by dmsimard** [comment]
> Then about the "task pop-down", it's actually a wish for the "Tasks results" list. The idea is to get tasks details on the same page to avoid opening new windows. For example the last failed task could automatically show its details below, and clicking on a task row could show a tooltip/dropdown box with the task detail so that it's easy to investigate a playbook run using a single browser tab.

So we had something similar to what you mention in the alpha implementation ([see the video](https://youtu.be/K3jTqgm2YuY?t=24)) but the challenge is that each task may or may not be run for the hosts and if you have many hosts, this sort of list display becomes quickly very, very crowded.

Maybe there is a middle ground that is worth looking into.
Right now, just a random idea like that, we could have a mouse over small popup of sorts over the task rows. When you mouse over it, it gives you a small snapshot that looks like this:

    host1: OK
    host2: skipped
    host3: failed

You could then click details like we do now to go to the detailed output of the tasks for the hosts.

**Comment by dmsimard** [comment]
Hi, I'm migrating the github issues to StoryBoard, the task tracker we'll be using.
The complete list of issues is available here: https://storyboard.openstack.org/#!/project/843

This has been mostly addressed. I've opened a task about contextual additional information here: https://storyboard.openstack.org/#!/story/2000750
