### ISSUE TITLE
Provide a proper way to configure the database (and other settings?)

### ISSUE THREAD

**Issue by dmsimard** [dmsimard/ara#9]
Right now we have to edit the __init__.py file to edit the database location, it's not exactly awesome.
We could take a similar approach to ansible with configuration file priority, i.e,:

    <cwd>/.ara.cfg
    ~/.ara.cfg
    /etc/ara/ara.cfg

**Comment by larsks** [comment]
Since this is meant to work with ansible, why not read configuration from the ansible configuration file?  You can add arbitrary sections to `ansible.cfg` and ansible will ignore them.  You can ask ansible to load the configuration file via the `ansible.constants.load_config_file` method, which gets you a `ConfigParser` object.

**Comment by dmsimard** [comment]
I thought about that too. It'd make sense from the callback perspective but would be sort of awkward if the web interface is hosted elsewhere (i.e, would need to make ansible a hard dependency and have a /etc/ansible/ansible.cfg on a webserver).

**Comment by larsks** [comment]
Never default to `/etc`!  Assume that you're going to be running from an unprivileged user account and default to something like "the current directory", or require the path to the config file to be explicit (e.g., via an environment variable, cli option, etc).

**Comment by dmsimard** [comment]
Fixed by https://github.com/dmsimard/ara/commit/18438c5566a81ec61c0a4a35b1919a84a7ac9d2b
